language: python

sudo: false

python:
   - "2.7"
   - "3.3"
   - "3.4"
   - "3.5"
   - "3.6"

before_install:
   - pip install flake8 python-coveralls mock coverage

script:
   - make test
   - make lint

after_success:
   - coveralls
